obj-$(CONFIG_LED_DRIVER)	+= sky_led_driver.o
obj-$(CONFIG_KEY_DRIVER)	+= sky_key_driver.o
obj-$(CONFIG_AP3216C_DRIVER)	+= sky_ap3216c_driver.o
obj-$(CONFIG_OLED_DRIVER)	+= sky_oled_operation.o sky_oled_platform.o